CUSTOM_ROLES = [
    {"role_name": "Customer & Supplier Creator", "desk_access": 1},
    {"role_name": "Purchase MRN Creator", "desk_access": 1},
    {"role_name": "Stock Notice Receiver", "desk_access": 1},
    {"role_name": "POS Manager", "desk_access": 1},
    {"role_name": "Prasadam Coupon Checker", "desk_access": 1},
    {"role_name": "Account Ledger Seer", "desk_access": 1},
    {"role_name": "DCC Manager", "desk_access": 1},
    {"role_name": "Task Giver", "desk_access": 1},
    {"role_name": "Item Manager", "desk_access": 1},
    {"role_name": "Sales Executive", "desk_access": 1},
    {"role_name": "Stock Checker", "desk_access": 1},
    {"role_name": "Purchase Order Approver", "desk_access": 1},
    {"role_name": "MRN Approver", "desk_access": 1},
    {"role_name": "IT Manager", "desk_access": 1},
    {"role_name": "MRN Raiser", "desk_access": 1},
]
