CUSTOM_FIELDS = {
    "Company": {
        "fieldname": "donation_suspense_account",
        "label": "Donation Suspense Account",
        "fieldtype": "Link",
        "insert_after": "unrealized_profit_loss_account",
        "options": "Account",
    },
    "Employee": {
        "fieldname": "father_or_spouse_name",
        "fieldtype": "Data",
        "insert_after": "employee_name",
        "label": "Father Or Spouse Name",
        "translatable": "1",
        "unique": "0",
    },
    "FOLK Donation": {
        "fetch_from": "folk_student.folk_guide",
        "fieldname": "folk_guide",
        "fieldtype": "Data",
        "in_list_view": "1",
        "insert_after": "folk_student",
        "label": "FOLK Guide",
        "read_only": "1",
        "unique": "0",
    },
    "Item": [
        {
            "fieldname": "selling_rate_with_gst",
            "fieldtype": "Data",
            "insert_after": "standard_rate",
            "label": "Selling Rate with GST",
            "read_only": "1",
            "translatable": "1",
            "unique": "0",
        },
        {
            "fieldname": "item_creation_request",
            "fieldtype": "Link",
            "options": "Item Creation Request",
            "insert_after": "total_projected_qty",
            "label": "Item Creation Request",
            "read_only": "1",
            "translatable": "1",
            "unique": "0",
        },
    ],
    "Item Group": [
        {
            "fieldname": "item_code_series",
            "label": "Item Code Series",
            "insert_after": "image",
            "fieldtype": "Data",
            "mandatory_depends_on": "eval:!doc.is_group",
            "allow_in_quick_entry": 1,
        },
        {
            "label": "Live Counter No",
            "fieldname": "live_counter_no",
            "insert_after": "is_group",
            "fieldtype": "Int",
            "non_negative": 1,
            "description": "To be used for Restaurant POS Billing",
            "in_list_view": 1,
        },
    ],
    "Journal Entry": [
        {
            "fieldname": "reference_bank",
            "fieldtype": "Data",
            "insert_after": "cheque_date",
            "label": "Reference Bank",
            "unique": "0",
        },
        {
            "label": "Bank Statement Name",
            "fieldname": "bank_statement_name",
            "insert_after": "donation_receipt",
            "length": 0,
            "fieldtype": "Data",
            "read_only": 1,
            "hidden": 1,
            "translatable": 1,
        },
        {
            "collapsible": "1",
            "fieldname": "section_suspense_clearance",
            "fieldtype": "Section Break",
            "insert_after": "amended_from",
            "label": "Suspense Clearance Detail",
            "unique": "0",
        },
        {
            "allow_on_submit": "1",
            "fieldname": "cleared_amount",
            "fieldtype": "Currency",
            "insert_after": "section_suspense_clearance",
            "label": "Cleared Amount",
            "no_copy": "1",
            "options": "Company:company:default_currency",
            "read_only": "1",
            "unique": "0",
        },
        {
            "fieldname": "cb_suspense_clearance_01",
            "fieldtype": "Column Break",
            "insert_after": "cleared_amount",
            "unique": "0",
        },
        {
            "allow_on_submit": "1",
            "fieldname": "uncleared_amount",
            "fieldtype": "Currency",
            "insert_after": "cb_suspense_clearance_01",
            "label": "Uncleared Amount",
            "no_copy": "1",
            "options": "Company:company:default_currency",
            "read_only": "1",
            "unique": "0",
        },
    ],
    "Journal Entry Account": [
        {
            "bold": "1",
            "fieldname": "donation_reference",
            "fieldtype": "Section Break",
            "insert_after": "against_account",
            "label": "Donation Reference",
            "unique": "0",
        },
        {
            "allow_on_submit": "1",
            "fieldname": "is_a_donation",
            "fieldtype": "Check",
            "in_list_view": "1",
            "in_standard_filter": "1",
            "insert_after": "donation_reference",
            "label": "Is a Donation",
            "unique": "0",
        },
        {
            "depends_on": "eval:doc.is_a_donation==true",
            "fieldname": "dr_no",
            "fieldtype": "Data",
            "in_list_view": "1",
            "insert_after": "is_folk",
            "label": "DR No",
            "unique": "0",
        },
        {
            "depends_on": "eval:doc.is_a_donation==true",
            "fieldname": "donor_name",
            "fieldtype": "Data",
            "insert_after": "dr_no",
            "label": "Donor Name",
            "translatable": "1",
            "unique": "0",
        },
        {
            "fieldname": "column_break_34",
            "fieldtype": "Column Break",
            "insert_after": "donor_name",
            "unique": "0",
        },
        {
            "depends_on": "eval:doc.is_a_donation==true",
            "fieldname": "receipt_date",
            "fieldtype": "Date",
            "insert_after": "column_break_34",
            "label": "Receipt Date",
            "unique": "0",
        },
        {
            "allow_on_submit": "1",
            "fieldname": "suspense_jv",
            "fieldtype": "Link",
            "insert_after": "receipt_date",
            "label": "Suspense JV",
            "options": "Journal Entry",
            "unique": "0",
        },
        {
            "allow_on_submit": "1",
            "fieldname": "online_payment_reference",
            "fieldtype": "Data",
            "insert_after": "suspense_jv",
            "label": "Online Payment Reference",
            "translatable": "1",
            "unique": "0",
        },
    ],
    "Material Request": [
        {
            "allow_on_submit": "1",
            "fieldname": "workflow_state",
            "fieldtype": "Link",
            "hidden": "1",
            "in_list_view": "1",
            "in_standard_filter": "1",
            "label": "Workflow State",
            "no_copy": "1",
            "options": "Workflow State",
            "unique": "0",
        },
        {
            "allow_on_submit": "1",
            "fieldname": "completed",
            "fieldtype": "Check",
            "insert_after": "naming_series",
            "label": "Completed",
            "read_only_depends_on": "eval:doc.completed != user",
            "unique": "0",
        },
        {
            "bold": "1",
            "depends_on": "eval:doc.material_request_type == 'Purchase'",
            "fieldname": "for_a_work_order",
            "fieldtype": "Check",
            "in_standard_filter": "1",
            "insert_after": "material_request_type",
            "label": "For a Work Order",
            "unique": "0",
        },
        {
            "fieldname": "purpose",
            "fieldtype": "Data",
            "in_standard_filter": "1",
            "insert_after": "for_a_work_order",
            "label": "Purpose",
            "reqd": "1",
            "translatable": "1",
            "unique": "0",
        },
        {
            "description": "Write down the description of PURPOSE, if detailing is required.",
            "fieldname": "description",
            "fieldtype": "Long Text",
            "insert_after": "purpose",
            "label": "Purpose Description",
            "unique": "0",
        },
        {
            "fieldname": "department",
            "fieldtype": "Link",
            "insert_after": "company",
            "label": "Department",
            "options": "Department",
            "reqd": "1",
            "unique": "0",
        },
        {
            "allow_on_submit": "1",
            "depends_on": "eval:doc.material_request_type=='Material Issue'",
            "fieldname": "material_purchase_link",
            "fieldtype": "Link",
            "insert_after": "department",
            "label": "Material Purchase Link",
            "options": "Material Request",
            "permlevel": "2",
            "unique": "0",
        },
        {
            "fieldname": "work_head",
            "fieldtype": "Link",
            "insert_after": "purpose_description",
            "label": "Work Head",
            "options": "Work Request Head",
        },
        {
            "fieldname": "boq",
            "fieldtype": "Link",
            "insert_after": "job_card",
            "label": "BOQ",
            "options": "BOQ",
        },
    ],
    "Material Request Item": [
        {
            "fieldname": "item_description",
            "fieldtype": "Data",
            "insert_after": "section_break_4",
            "label": "Item Description",
            "length": "256",
            "translatable": "1",
            "unique": "0",
        },
        {
            "fieldname": "item_type",
            "fieldtype": "Data",
            "insert_after": "item_name",
            "label": "Item Type",
            "translatable": "1",
            "read_only": "1",
            "in_list_view": "1",
        },
    ],
    "Purchase Order Item": [
        {
            "fieldname": "item_type",
            "fieldtype": "Data",
            "insert_after": "item_name",
            "label": "Item Type",
            "translatable": "1",
            "read_only": "1",
            "in_list_view": "1",
        },
    ],
    "POS Invoice": {
        "fetch_from": "company.abbr",
        "fieldname": "company_abbreviation",
        "fieldtype": "Data",
        "hidden": "1",
        "insert_after": "against_income_account",
        "label": "Company Abbreviation",
        "translatable": "1",
        "unique": "0",
    },
    "Purchase Invoice": [
        {
            "fieldname": "department",
            "fieldtype": "Link",
            "in_standard_filter": "1",
            "insert_after": "amended_from",
            "label": "Department",
            "options": "Department",
            "read_only": "1",
            "unique": "0",
        },
        {
            "label": "Default Difference Account",
            "fieldname": "default_difference_account",
            "insert_after": "items_section",
            "length": 0,
            "fieldtype": "Link",
            "options": "Account",
        },
        {
            "fieldname": "expense_account",
            "fieldtype": "Link",
            "insert_after": "column_break_63",
            "label": "Expense Account",
            "options": "Account",
            "unique": "0",
        },
    ],
    "Purchase Order": [
        {
            "label": "For a Work Order",
            "fieldname": "for_a_work_order",
            "insert_after": "type",
            "fieldtype": "Check",
            "read_only": 1,
            "in_standard_filter": 1,
            "bold": 1,
        },
        {
            "allow_on_submit": "1",
            "fieldname": "workflow_state",
            "fieldtype": "Link",
            "hidden": "1",
            "in_list_view": "1",
            "in_standard_filter": "1",
            "label": "Workflow State",
            "no_copy": "1",
            "options": "Workflow State",
            "unique": "0",
        },
        {
            "description": "Type of Expenditure.\nCAPEX is an amount spent to acquire or improve a long-term asset such as any electronics equipment.\nREVEX refers to expenses incurred in the course of ordinary business, such as sales, general and administrative expenses.",
            "fieldname": "type",
            "fieldtype": "Select",
            "in_standard_filter": "1",
            "insert_after": "supplier",
            "label": "Type",
            "options": "REVEX\nCAPEX",
            "reqd": "1",
            "translatable": "1",
            "unique": "0",
        },
        {
            "depends_on": "eval: doc.supplier == 'One time Vendor'",
            "fieldname": "one_time_vendor_section",
            "fieldtype": "Section Break",
            "insert_after": "type",
            "label": "One Time Vendor Details",
            "unique": "0",
        },
        {
            "fieldname": "one_time_vendor_address",
            "fieldtype": "Data",
            "insert_after": "one_time_vendor_section",
            "label": "One Time Vendor Address",
            "unique": "0",
        },
        {
            "fieldname": "company_details",
            "fieldtype": "Section Break",
            "insert_after": "one_time_vendor_address",
            "label": "Company Details",
            "unique": "0",
        },
        {
            "fieldname": "alm",
            "fieldtype": "Section Break",
            "insert_after": "schedule_date",
            "label": "ALM",
            "unique": "0",
        },
        {
            "fieldname": "prepared_by",
            "fieldtype": "Data",
            "insert_after": "alm",
            "label": "Prepared By",
            "options": "Email",
            "read_only": "1",
            "unique": "0",
        },
        {
            "fieldname": "checked_by",
            "fieldtype": "Data",
            "insert_after": "prepared_by",
            "label": "Checked By",
            "options": "Email",
            "read_only": "1",
            "unique": "0",
        },
        {
            "fieldname": "alm_column_break",
            "fieldtype": "Column Break",
            "insert_after": "checked_by",
            "unique": "0",
        },
        {
            "fieldname": "recommended_by",
            "fieldtype": "Data",
            "insert_after": "alm_column_break",
            "label": "Recommended By",
            "options": "Email",
            "read_only": "1",
            "unique": "0",
        },
        {
            "fieldname": "first_approving_authority",
            "fieldtype": "Data",
            "insert_after": "recommended_by",
            "label": "First Approving Authority",
            "options": "Email",
            "read_only": "1",
            "unique": "0",
        },
        {
            "fieldname": "final_approving_authority",
            "fieldtype": "Data",
            "insert_after": "first_approving_authority",
            "label": "Final Approving Authority",
            "options": "Email",
            "read_only": "1",
            "unique": "0",
        },
        {
            "fetch_from": "material_request.department",
            "fieldname": "department",
            "fieldtype": "Link",
            "insert_after": "company",
            "label": "Department",
            "options": "Department",
            "reqd": "1",
            "unique": "0",
        },
        {
            "allow_in_quick_entry": "1",
            "fieldname": "comparison_sheet",
            "fieldtype": "Attach",
            "insert_after": "department",
            "label": "Comparison Sheet",
            "unique": "0",
        },
        {
            "fieldname": "extra_description",
            "fieldtype": "Long Text",
            "insert_after": "items",
            "label": "Extra Description",
            "unique": "0",
        },
        {
            "bold": "1",
            "default": "(This is a computer generated Document and does not require a physical signature.)",
            "fieldname": "signature_note",
            "fieldtype": "Data",
            "insert_after": "update_auto_repeat_reference",
            "label": "Signature Note",
            "read_only": "1",
            "translatable": "1",
            "unique": "0",
        },
        {
            "label":"For a Work Order",
            "fieldname":"for_a_work_order",
            "insert_after":"type",
            "fieldtype":"Check",
            "read_only":1,
           "in_standard_filter":1,"bold":1}
    ],
    "Purchase Receipt": {
        "fieldname": "department",
        "fieldtype": "Link",
        "insert_after": "is_return",
        "label": "Department",
        "options": "Department",
        "read_only": "1",
        "unique": "0",
    },
    "Purchase Receipt Item": {
        "allow_on_submit": "1",
        "fieldname": "do_not_print_in_barcodes",
        "fieldtype": "Check",
        "insert_after": "item_name",
        "label": "Do Not Print in Barcodes",
        "unique": "0",
    },
    "Supplier": [
        {
            "fieldname": "supplier_creation_request",
            "fieldtype": "Link",
            "options": "Supplier Creation Request",
            "insert_after": "is_frozen",
            "label": "Supplier Creation Request",
            "read_only": "1",
            "translatable": "1",
            "unique": "0",
        }
    ],
    "Stock Entry": {
        "dt": "Stock Entry",
        "fieldname": "default_difference_account",
        "fieldtype": "Link",
        "insert_after": "source_address_display",
        "label": "Default Difference Account",
        "mandatory_depends_on": "eval:doc.purpose=='Material Issue' || doc.purpose=='Material Receipt'",
        "options": "Account",
        "unique": "0",
    },
    "Task": [
        {
            "fieldname": "to_department",
            "fieldtype": "Select",
            "in_standard_filter": "1",
            "label": "To Department",
            "options": "Maintenance\nIT",
            "translatable": "1",
            "unique": "0",
        },
        {
            "fieldname": "contact_person",
            "fieldtype": "Data",
            "insert_after": "subject",
            "label": "Contact Person",
            "translatable": "1",
            "unique": "0",
        },
        {
            "fieldname": "contact_mobile_no",
            "fieldtype": "Data",
            "insert_after": "contact_person",
            "label": "Contact Mobile No",
            "translatable": "1",
            "unique": "0",
        },
        {
            "fieldname": "workflow_state",
            "fieldtype": "Select",
            "hidden": "1",
            "in_standard_filter": "1",
            "insert_after": "project",
            "label": "workflow_state",
            "options": "Draft\nAcknowledged\nCompleted\nUser Confirmed",
            "translatable": "1",
            "unique": "0",
        },
        {
            "fieldname": "location",
            "fieldtype": "Data",
            "in_list_view": "1",
            "in_standard_filter": "1",
            "insert_after": "completed_by",
            "label": "Location",
            "translatable": "1",
            "unique": "0",
        },
    ],
}
